services:
  db:
    image: postgres:16.1-alpine
    restart: always
    environment:
      POSTGRES_DB: 'devcompany'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'spring'
    ports:
      - '5434:5432'